# Generated by Django 3.2.4 on 2021-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
