# Generated by Django 3.2.4 on 2021-06-17 06:07

from django.db import migrations, models
import zshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_settings', '0003_sitesetting_copy_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=zshop_settings.models.upload_image_path),
        ),
    ]
