# Generated by Django 3.2.4 on 2021-06-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_favorites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProducts',
        ),
    ]
