# Generated by Django 3.2.3 on 2021-05-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
