# Generated by Django 3.2.3 on 2021-05-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_products_category', '0001_initial'),
        ('zshop_products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='zshop_products_category.ProductCategory'),
        ),
    ]
