# Generated by Django 3.2.3 on 2021-06-05 07:50

from django.db import migrations, models
import django.db.models.deletion
import zshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_products', '0004_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=zshop_products.models.upload_gallery_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zshop_products.product')),
            ],
        ),
    ]
