# Generated by Django 3.2.3 on 2021-06-05 08:23

from django.db import migrations, models
import zshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_products', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=zshop_products.models.upload_gallery_image_path),
        ),
    ]
