# Generated by Django 3.2.4 on 2021-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_products', '0006_alter_productgallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(null=True),
        ),
    ]
