# Generated by Django 3.2.4 on 2021-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_products', '0007_product_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
