# Generated by Django 3.2.4 on 2021-10-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zshop_products', '0009_product_favorites'),
        ('zshop_comments', '0004_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zshop_products.product'),
        ),
    ]
